language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - mypy lemon
  - pycodestyle --exclude docs/ --ignore E501
  - coverage run --source=lemon setup.py test
  - coveralls
notifications:
  webhooks: https://app.fossa.io/hooks/travisci
